function [matrix,vec] = ImportMatrix(filename)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   INITIALEMISSION = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   INITIALEMISSION = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data
%   from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   initialemission = importfile('initial_emission.tsv', 2, 4);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/12/25 14:29:16

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

fid = fopen(filename);
tline = fgets(fid);
[~, matches] = strsplit(tline,'\t');

%% Format string for each line of text:
%   column2: double (%f)
%	column3: double (%f)
%   column4: double (%f)
%	column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%f';
formatSpecS = '%s%';
startRowS = 1;

for col = 1: length(matches) -1
    formatSpec = strcat(formatSpec, '%f');
    formatSpecS = strcat(formatSpecS, '*s%');
end    

formatSpec = strcat(formatSpec,  '%[^\n\r]');
formatSpecS = strcat(formatSpecS,  '[^\n\r]');



%% Open the text file.

fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);

for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

dataArrayS = textscan(fileID, formatSpecS, endRow(1)-startRowS(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRowS(1)-1, 'ReturnOnError', false);
for block=1:length(startRowS)
    frewind(fileID);
    dataArrayBlockS = textscan(fileID, formatSpecS, endRow(block)-startRowS(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRowS(block)-1, 'ReturnOnError', false);
    dataArrayS{1} = [dataArrayS{1};dataArrayBlockS{1}];
end



%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
matrix = [dataArray{1:end-1}];
tmpVec = [dataArrayS{:, 1}];
vec = tmpVec(2:end);
